# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=60)),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
    ]
